In [1]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
import pandas as pd
import numpy as np
import pytz

In [2]:
from API.get_data.api_yahoo import get_historical_data, get_analyst_price_targets, get_business_recommendation, get_business_grades
from utils.trends import get_trends_events

In [3]:
df = get_historical_data("TSLA", "5y")

In [4]:
df_2 =df.copy()

In [5]:
df_2

,Date,Year,Month,Day,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2020-07-06 00:00:00-04:00,2020,7,6,85.112663,91.852669,84.402664,91.438667,308548500,0.0,0.0
1,2020-07-07 00:00:00-04:00,2020,7,7,93.667336,95.300003,89.113998,92.657333,322345500,0.0,0.0
2,2020-07-08 00:00:00-04:00,2020,7,8,93.666664,94.484001,87.422668,91.058670,244669500,0.0,0.0
3,2020-07-09 00:00:00-04:00,2020,7,9,93.132668,93.903999,90.085335,92.952003,175764000,0.0,0.0
4,2020-07-10 00:00:00-04:00,2020,7,10,93.066666,103.261330,91.734001,102.976669,350064000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1251,2025-06-27 00:00:00-04:00,2025,6,27,324.510010,329.339996,317.500000,323.630005,89067000,0.0,0.0
1252,2025-06-30 00:00:00-04:00,2025,6,30,319.899994,325.579987,316.600006,317.660004,76695100,0.0,0.0
1253,2025-07-01 00:00:00-04:00,2025,7,1,298.459991,305.890015,293.209991,300.709991,145085700,0.0,0.0
1254,2025-07-02 00:00:00-04:00,2025,7,2,312.630005,316.829987,303.820007,315.649994,119483700,0.0,0.0
1255,2025-07-03 00:00:00-04:00,2025,7,3,317.989990,318.450012,312.760010,315.350006,58042300,0.0,0.0

In [6]:
# today = datetime.now()#.strftime('%Y-%m-%d')
# first_of_this_month = today.replace(day=1)
# first_of_last_month = first_of_this_month - relativedelta(months=1)
# first_of_last_month_time_stamp = pd.Timestamp(first_of_last_month)
# # Remettre l'heure à zéro (minuit)
# ts_midnight = first_of_last_month_time_stamp.replace(hour=0, minute=0, second=0, microsecond=0)

In [7]:
today = datetime.now()#.strftime('%Y-%m-%d')
first_of_this_month = today.replace(day=1)
first_of_last_month = first_of_this_month - relativedelta(months=1)
# Remettre l'heure à zéro (minuit)
first_of_this_month_midnight = first_of_this_month.replace(hour=0, minute=0, second=0, microsecond=0)
first_of_last_month_midnight = first_of_last_month.replace(hour=0, minute=0, second=0, microsecond=0)
one_year_rolling = today - relativedelta(months=12)
one_year_rolling_midnight = one_year_rolling.replace(hour=0, minute=0, second=0, microsecond=0)
# five_year_rolling = today - relativedelta(year=5)
# five_year_rolling_midnight = five_year_rolling.replace(hour=0, minute=0, second=0, microsecond=0)
year_to_date_midnight = datetime(first_of_this_month.year, 1, 1, 0, 0)

In [8]:
five_year_rolling = today - relativedelta(years=5)
five_year_rolling_midnight = five_year_rolling.replace(hour=0, minute=0, second=0, microsecond=0)

In [9]:
df["Date"] = df["Date"].apply(lambda x: x.tz_localize(None))

In [10]:
this_month_data = df[df["Date"]>=first_of_this_month_midnight]

In [11]:
last_month_data = df[df["Date"]>=first_of_last_month_midnight]

In [12]:
year_to_date_data = df[df["Date"]>=year_to_date_midnight]

In [13]:
one_year_rolling_period_data = df[df["Date"]>=one_year_rolling_midnight]

In [14]:
five_year_rolling_period_data = df[df["Date"]>=five_year_rolling_midnight]

tendance sur  
- mois   
- year to date   
- N-1  
- 5 ans  
- 10 ans

In [15]:
get_trends_events(
    x=df.index.values, y=df["Open"],
    degre=6,
    show_curve=True)

TypeError: get_trends_events() got an unexpected keyword argument 'x'

In [ ]:
get_trends_events(
    x=df.index.values, y=df["Low"],
    degre=6,
    show_curve=True)

In [ ]:
from utils.trends_candles import candlestick_price_chart

In [17]:
df

,Date,Year,Month,Day,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2020-07-06,2020,7,6,85.112663,91.852669,84.402664,91.438667,308548500,0.0,0.0
1,2020-07-07,2020,7,7,93.667336,95.300003,89.113998,92.657333,322345500,0.0,0.0
2,2020-07-08,2020,7,8,93.666664,94.484001,87.422668,91.058670,244669500,0.0,0.0
3,2020-07-09,2020,7,9,93.132668,93.903999,90.085335,92.952003,175764000,0.0,0.0
4,2020-07-10,2020,7,10,93.066666,103.261330,91.734001,102.976669,350064000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1251,2025-06-27,2025,6,27,324.510010,329.339996,317.500000,323.630005,89067000,0.0,0.0
1252,2025-06-30,2025,6,30,319.899994,325.579987,316.600006,317.660004,76695100,0.0,0.0
1253,2025-07-01,2025,7,1,298.459991,305.890015,293.209991,300.709991,145085700,0.0,0.0
1254,2025-07-02,2025,7,2,312.630005,316.829987,303.820007,315.649994,119483700,0.0,0.0
1255,2025-07-03,2025,7,3,317.989990,318.450012,312.760010,315.350006,58042300,0.0,0.0

In [16]:
get_trends_events(
    df=df,
    cols = ["Open", "Low", "High", "Close"],
    degre=6,
    show_curve=True,
    colors = {
        "Open": "blue",
        "Low": "red",
        "High": "green",
        "Close": "orange"
    }
)

{'Open_slope': np.float64(0.17495127380681993),
 'Low_slope': np.float64(0.17256229142348112),
 'High_slope': np.float64(0.17750345326503578),
 'Close_slope': np.float64(0.1749589990003311)}

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# Tracé
df.set_index('Date', inplace=True)
plt.figure(figsize=(12, 6))
plt.plot(df.index, df['Open'], label='Open', color='blue')
plt.plot(df.index, df['High'], label='High', color='green')
plt.plot(df.index, df['Low'], label='Low', color='red')
plt.plot(df.index, df['Close'], label='Close', color='orange')

plt.title("Évolution des prix")
plt.xlabel("Date")
plt.ylabel("Prix")

In [ ]:
df

---

In [ ]:
# fonction a rajouter a get info company preporcessing -- info business

In [ ]:
period        sell  strongBuy  strongSell symbol
2025-04-01     9          9           3   TSLA

In [ ]:
9/(9+9+3)

In [ ]:
9/(7+16+14+9+2)

In [ ]:
import numpy as np
def u(df_trend):
    df_trend["sell"] = df_trend["sell"] / total_recommendation
    df_trend["strongBuy"] = df_trend["strongBuy"] / total_recommendation
    df_trend["strongSell"] = df_trend["strongSell"] / total_recommendation
    mean_sell = np.round(df_trend["sell"].mean(),2)
    mean_strongBuy = np.round(df_trend["strongBuy"].mean(),2)
    mean_strongSell = np.round(df_trend["strongSell"].mean(),2)

In [ ]:
get_business_recommendation("TSLA")

In [ ]:
get_business_grades("AAPL")

In [ ]:
get_analyst_price_targets("AAPL")