In [1]:
from API.get_data.api_finnhub import get_competitor, recommendation_trends, insider_sentiment, info_company
from datetime import datetime, timedelta

In [2]:
get_competitor("TSLA")

['TSLA', 'GM', 'F', 'RIVN', 'LCID', 'THO', 'NWTN', 'WGO', 'FFIE', 'CENN']

In [3]:
def summarize_recommendation_trends(business_ticker):
    df_trend = recommendation_trends("business_ticker")

In [4]:
a = recommendation_trends("TSLA")
a

   buy  hold      period  sell  strongBuy  strongSell symbol
0   19    17  2025-03-01     9         10           5   TSLA
1   19    17  2025-02-01     9          9           4   TSLA
2   19    17  2025-01-01     9         10           5   TSLA
3   18    19  2024-12-01     9         10           4   TSLA

In [5]:
mean_buy = a["buy"].mean()
mean_strongBuy = a["strongBuy"].mean()
mean_hold = a["hold"].mean()
mean_sell = a["sell"].mean()
mean_strongSell = a["strongSell"].mean()

In [6]:
a.loc[a.shape[0]-1, "period"]

'2024-12-01'

In [7]:
a.loc[0, "period"] - a.loc[a.shape[0]-1, "period"]

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [8]:
from_date = (datetime.now() - timedelta(days=200)).strftime('%Y-%m-%d')
today = datetime.now().strftime('%Y-%m-%d')
a = insider_sentiment("TSLA", from_date, today)

In [9]:
a

  symbol  year  month  change        mspr
0   TSLA  2024      1  -38160 -100.000000
1   TSLA  2024      2 -104206  -33.333332
2   TSLA  2024      3  -94392  -32.881410
3   TSLA  2024      4  -10500  -33.333332
4   TSLA  2024      5  -93705  -33.333332
5   TSLA  2024      6    -650   -0.128470
6   TSLA  2024      7  -66364  -19.571090

In [10]:
info_company("TSLA")

  country currency finnhubIndustry  marketCapitalization
0      US      USD     Automobiles         799979.946815