In [1]:
import json
from pathlib import Path
from typing import Dict, Any
from datetime import date
from  API.preprocessing.get_historical_stock_preprocessing import historical_stock_info
from API.preprocessing.get_company_news_preprocessing import create_news_dataset
from  API.preprocessing.get_news_country_preprocessing import get_news_country
from  API.preprocessing.get_info_company_preprocessing import get_info_company_preprocessing
from  API.preprocessing.get_options_preprocessing import create_options_dataset

In [2]:
def save_json(data: Dict[str, Any], filepath: str) -> None:
    """
    Save an dict object in an json file

    Args:
        data (dict): the data to save 
        filepath (str): the path in which the json file is created
    """
    path = Path(filepath)
    try:
        with path.open("w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"Data save at : {path.resolve()}")
    except Exception as e:
        print(f"Error whan saving the file : {e}")

In [ ]:
def regroupe_all_dataset(business_ticker, business_name):
    info_company = get_info_company_preprocessing(business_ticker)
    company_news = create_news_dataset(business_name=business_name, business_ticker=business_ticker)
    country_news = get_news_country()
    historical_stock = historical_stock_info(business_ticker)
    options = create_options_dataset(business_ticker)
    today = date.today().strftime("%Y_%m_%d")
    data = {
        "info_company":info_company,
        "news": {
            "company_news":company_news,
            "country_news":country_news
        },
        "historical_stock_info":historical_stock,
        "options":options
    }
    filepath = f'..\data\output\all_data_regroup\data_{today}.json'
    save_json(data=data, filepath=filepath)
    return data

<>:17: SyntaxWarning: invalid escape sequence '\d'
<>:17: SyntaxWarning: invalid escape sequence '\d'
C:\Users\cleme\AppData\Local\Temp\ipykernel_15976\1175288933.py:17: SyntaxWarning: invalid escape sequence '\d'
  filepath = f'..\data\output\dataset\data_{today}.json'

In [4]:
a = regroupe_all_dataset("MSFT", "Microsoft")

Date des articles de récupération des articles 2025-06-24
News recover from api_news_org
News sur 6 days 14:45:34 jours
News recover from finhub
News processing done and save
News sur 4 days 16:30:00 jours

c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\utils\trends_slope.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_name["EMA"] = df_name["Close"].ewm(span=ema_period, adjust=False).mean()
c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\utils\trends_slope.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_name["EMA_Slope"] = (
c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\utils\trends_slope.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_name["EMA_Direction_Slope"] = np.select(
c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\utils\trends_slope.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_name["EMA"] = df_name["Close"].ewm(span=ema_period, adjust=False).mean()
c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\utils\trends_slope.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_name["EMA_Slope"] = (
c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\utils\trends_slope.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_name["EMA_Direction_Slope"] = np.select(
c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\utils\trends_slope.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_name["EMA"] = df_name["Close"].ewm(span=ema_period, adjust=False).mean()
c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\utils\trends_slope.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_name["EMA_Slope"] = (
c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\utils\trends_slope.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_name["EMA_Direction_Slope"] = np.select(
c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\utils\trends_slope.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_name["EMA"] = df_name["Close"].ewm(span=ema_period, adjust=False).mean()
c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\utils\trends_slope.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_name["EMA_Slope"] = (
c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\utils\trends_slope.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_name["EMA_Direction_Slope"] = np.select(
c:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\SRC\API\preprocessing\get_historical_stock_preprocessing.py:84: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ].replace(replace_map)

Sentiment moyen des analystes : 0.93
test
Expirations Dates of the options ('2025-07-11', '2025-07-18', '2025-07-25', '2025-08-01', '2025-08-08', '2025-08-15', '2025-08-22', '2025-09-19', '2025-10-17', '2025-12-19', '2026-01-16', '2026-02-20', '2026-03-20', '2026-05-15', '2026-06-18', '2026-09-18', '2026-12-18', '2027-01-15', '2027-06-17', '2027-12-17')
Data save at : C:\Users\cleme\Documents\Ynov\M2\Projet Master\Projet Bourse\NEW\Projet_master\data\output\dataset\data_2025_07_08.json

In [ ]:
import json
import pandas as pd

In [ ]:
# Read JSON file
with open('..\data\output\dataset\data_2025_07_08.json', "r", encoding="utf-8") as f:
    output_data = json.load(f)

# Use the output_data
print(output_data)

{'info_company': '{"country":{"0":"US"},"currency":{"0":"USD"},"finnhubIndustry":{"0":"Technology"},"marketCapitalization":{"0":3699325.7453033621},"competitor_lst":{"0":"MSFT, ORCL, NOW, PANW, CRWD, FTNT, ZS, GEN, RBRK, CVLT"},"begin_analyst_period":{"0":"2025-04-01"},"end_analyst_period":{"0":"2025-07-01"},"delta_number_days_analyst":{"0":91},"mean_sell":{"0":0.0},"mean_strongBuy":{"0":1.0},"mean_strongSell":{"0":0.0},"insider_sentiment":{"0":-1}}', 'news': {'company_news': '{"index":{"0":0,"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10,"11":11,"12":12,"13":13,"14":14,"15":15,"16":16,"17":17,"18":18,"19":19,"20":20,"21":21,"22":22,"23":23,"24":24,"25":25,"26":26,"27":83,"28":84,"29":27,"30":28,"31":29,"32":30,"33":31,"34":32,"35":33,"36":34,"37":35,"38":36,"39":33,"40":37,"41":38,"42":39,"43":40,"44":41,"45":42,"46":43,"47":44,"48":45,"49":46,"50":47,"51":48,"52":49,"53":70,"54":31,"55":22,"56":50,"57":51,"58":52,"59":53,"60":54,"61":55,"62":56,"63":57,"64":58,"65":59,"66":60,"67":61,"68":62,"69":63,"70":64,"71":65,"72":66,"73":67,"74":78,"75":16,"76":52,"77":56,"78":68,"79":69,"80":70,"81":71,"82":73,"83":74,"84":75,"85":76,"86":77,"87":78,"88":72,"89":79,"90":80,"91":81,"92":82,"93":83,"94":84,"95":85,"96":86,"97":87,"98":88,"99":89,"100":90,"101":91,"102":92,"103":93,"104":94,"105":95,"106":96,"107":97,"108":98,"109":99,"110":100,"111":101,"112":102,"113":103,"114":104,"115":105,"116":106,"117":107,"118":108,"119":109,"120":110,"121":111,"122":112,"123":69,"124":75,"125":11,"126":10,"127":55,"128":4,"129":77,"130":81,"131":26,"132":43,"133":24,"134":96,"135":113,"136":114,"137":116,"138":117,"139":118,"140":119,"141":120,"142":121,"143":122,"144":123,"145":124,"146":125,"147":126,"148":127,"149":128,"150":129,"151":130,"152":131,"153":133,"154":134,"155":135,"156":115,"157":136,"158":132,"159":137,"160":138,"161":139,"162":140,"163":141,"164":142,"165":143,"166":144,"167":145,"168":146,"169":147,"170":148,"171":149,"172":150,"173":151,"174":152,"175":93,"176":57,"177":89,"178":58,"179":2,"180":54,"181":68,"182":66,"183":82,"184":1,"185":35,"186":18,"187":20,"188":21,"189":23,"190":27,"191":28,"192":153,"193":154,"194":155,"195":156,"196":157,"197":158,"198":159,"199":160,"200":161,"201":162,"202":163,"203":164,"204":165,"205":166,"206":167,"207":168,"208":169,"209":170,"210":171,"211":172,"212":173,"213":175,"214":176,"215":177,"216":178,"217":179,"218":180,"219":181,"220":184,"221":182,"222":183,"223":185,"224":186,"225":187,"226":188,"227":189,"228":190,"229":174,"230":191,"231":192,"232":193,"233":194,"234":195,"235":76,"236":97,"237":95,"238":34,"239":41,"240":19,"241":46,"242":87,"243":9,"244":98,"245":79,"246":37,"247":51,"248":73,"249":17,"250":80,"251":88,"252":44,"253":12,"254":25,"255":15,"256":53,"257":39,"258":0,"259":63,"260":74,"261":90,"262":13,"263":64,"264":67,"265":71,"266":50,"267":72,"268":60,"269":45,"270":8,"271":7,"272":40,"273":29,"274":30,"275":5,"276":32,"277":99,"278":65,"279":91,"280":92,"281":49,"282":47,"283":48,"284":59,"285":61,"286":62,"287":14,"288":38,"289":85,"290":86,"291":42,"292":6,"293":94,"294":3,"295":36},"year":{"0":2025,"1":2025,"2":2025,"3":2025,"4":2025,"5":2025,"6":2025,"7":2025,"8":2025,"9":2025,"10":2025,"11":2025,"12":2025,"13":2025,"14":2025,"15":2025,"16":2025,"17":2025,"18":2025,"19":2025,"20":2025,"21":2025,"22":2025,"23":2025,"24":2025,"25":2025,"26":2025,"27":2025,"28":2025,"29":2025,"30":2025,"31":2025,"32":2025,"33":2025,"34":2025,"35":2025,"36":2025,"37":2025,"38":2025,"39":2025,"40":2025,"41":2025,"42":2025,"43":2025,"44":2025,"45":2025,"46":2025,"47":2025,"48":2025,"49":2025,"50":2025,"51":2025,"52":2025,"53":2025,"54":2025,"55":2025,"56":2025,"57":2025,"58":2025,"59":2025,"60":2025,"61":2025,"62":2025,"63":2025,"64":2025,"65":2025,"66":2025,"67":2025,"68":2025,"69":2025,"70":2025,"71":2025,"72":2025,"73":2025,"74":2025,"75":2025,"76":2025,"77":2025,"78":2025,"79":2025,"80":2025,"81":2025,"82":2025,"83":2025,"84":2025,"85":2025,"86":2025,"87":2025,"88":2025,"89":2025,"90":2025,"91":2025,"92":2025,"93":2025,"94":2025,"95":2025,"96":2025,"97":2025,"98":2025,"99":2025,"100":2025,"101":2025,"102":2025,"103":2025,"104":2025,"105":2025,"106":2025,"107":2025,"108":2025,"109":2025,"110":2025,"111":2025,"112":2025,"113":2025,"114":2025,"115":2025,"116":2025,"117":2025,"118":2025,"119":2025,"120":2025,"121":2025,"122":2025,"123":2025,"124":2025,"125":2025,"126":2025,"127":2025,"128":2025,"129":2025,"130":2025,"131":2025,"132":2025,"133":2025,"134":2025,"135":2025,"136":2025,"137":2025,"138":2025,"139":2025,"140":2025,"141":2025,"142":2025,"143":2025,"144":2025,"145":2025,"146":2025,"147":2025,"148":2025,"149":2025,"150":2025,"151":2025,"152":2025,"153":2025,"154":2025,"155":2025,"156":2025,"157":2025,"158":2025,"159":2025,"160":2025,"161":2025,"162":2025,"163":2025,"164":2025,"165":2025,"166":2025,"167":2025,"168":2025,"169":2025,"170":2025,"171":2025,"172":2025,"173":2025,"174":2025,"175":2025,"176":2025,"177":2025,"178":2025,"179":2025,"180":2025,"181":2025,"182":2025,"183":2025,"184":2025,"185":2025,"186":2025,"187":2025,"188":2025,"189":2025,"190":2025,"191":2025,"192":2025,"193":2025,"194":2025,"195":2025,"196":2025,"197":2025,"198":2025,"199":2025,"200":2025,"201":2025,"202":2025,"203":2025,"204":2025,"205":2025,"206":2025,"207":2025,"208":2025,"209":2025,"210":2025,"211":2025,"212":2025,"213":2025,"214":2025,"215":2025,"216":2025,"217":2025,"218":2025,"219":2025,"220":2025,"221":2025,"222":2025,"223":2025,"224":2025,"225":2025,"226":2025,"227":2025,"228":2025,"229":2025,"230":2025,"231":2025,"232":2025,"233":2025,"234":2025,"235":2025,"236":2025,"237":2025,"238":2025,"239":2025,"240":2025,"241":2025,"242":2025,"243":2025,"244":2025,"245":2025,"246":2025,"247":2025,"248":2025,"249":2025,"250":2025,"251":2025,"252":2025,"253":2025,"254":2025,"255":2025,"256":2025,"257":2025,"258":2025,"259":2025,"260":2025,"261":2025,"262":2025,"263":2025,"264":2025,"265":2025,"266":2025,"267":2025,"268":2025,"269":2025,"270":2025,"271":2025,"272":2025,"273":2025,"274":2025,"275":2025,"276":2025,"277":2025,"278":2025,"279":2025,"280":2025,"281":2025,"282":2025,"283":2025,"284":2025,"285":2025,"286":2025,"287":2025,"288":2025,"289":2025,"290":2025,"291":2025,"292":2025,"293":2025,"294":2025,"295":2025},"month":{"0":7,"1":7,"2":7,"3":7,"4":7,"5":7,"6":7,"7":7,"8":7,"9":7,"10":7,"11":7,"12":7,"13":7,"14":7,"15":7,"16":7,"17":7,"18":7,"19":7,"20":7,"21":7,"22":7,"23":7,"24":7,"25":7,"26":7,"27":7,"28":7,"29":7,"30":7,"31":7,"32":7,"33":7,"34":7,"35":7,"36":7,"37":7,"38":7,"39":7,"40":7,"41":7,"42":7,"43":7,"44":7,"45":7,"46":7,"47":7,"48":7,"49":7,"50":7,"51":7,"52":7,"53":7,"54":7,"55":7,"56":7,"57":7,"58":7,"59":7,"60":7,"61":7,"62":7,"63":7,"64":7,"65":7,"66":7,"67":7,"68":7,"69":7,"70":7,"71":7,"72":7,"73":7,"74":7,"75":7,"76":7,"77":7,"78":7,"79":7,"80":7,"81":7,"82":7,"83":7,"84":7,"85":7,"86":7,"87":7,"88":7,"89":7,"90":7,"91":7,"92":7,"93":7,"94":7,"95":7,"96":7,"97":7,"98":7,"99":7,"100":7,"101":7,"102":7,"103":7,"104":7,"105":7,"106":7,"107":7,"108":7,"109":7,"110":7,"111":7,"112":7,"113":7,"114":7,"115":7,"116":7,"117":7,"118":7,"119":7,"120":7,"121":7,"122":7,"123":7,"124":7,"125":7,"126":7,"127":7,"128":7,"129":7,"130":7,"131":7,"132":7,"133":7,"134":7,"135":7,"136":7,"137":7,"138":7,"139":7,"140":7,"141":7,"142":7,"143":7,"144":7,"145":7,"146":7,"147":7,"148":7,"149":7,"150":7,"151":7,"152":7,"153":7,"154":7,"155":7,"156":7,"157":7,"158":7,"159":7,"160":7,"161":7,"162":7,"163":7,"164":7,"165":7,"166":7,"167":7,"168":7,"169":7,"170":7,"171":7,"172":7,"173":7,"174":7,"175":7,"176":7,"177":7,"178":7,"179":7,"180":7,"181":7,"182":7,"183":7,"184":7,"185":7,"186":7,"187":7,"188":7,"189":7,"190":7,"191":7,"192":7,"193":7,"194":7,"195":7,"196":7,"197":7,"198":7,"199":7,"200":7,"201":7,"202":7,"203":7,"204":7,"205":7,"206":7,"207":7,"208":7,"209":7,"210":7,"211":7,"212":7,"213":7,"214":7,"215":7,"216":7,"217":7,"218":7,"219":7,"220":7,"221":7,"222":7,"223":7,"224":7,"225":7,"226":7,"227":7,"228":7,"229":7,"230":7,"231":7,"232":7,"233":7,"234":7,"235":7,"236":7,"237":7,"238":7,"239":7,"240":7,"241":7,"242":7,"243":7,"244":7,"245":7,"246":6,"247":6,"248":6,"249":6,"250":6,"251":6,"252":6,"253":6,"254":6,"255":6,"256":6,"257":6,"258":6,"259":6,"260":6,"261":6,"262":6,"263":6,"264":6,"265":6,"266":6,"267":6,"268":6,"269":6,"270":6,"271":6,"272":6,"273":6,"274":6,"275":6,"276":6,"277":6,"278":6,"279":6,"280":6,"281":6,"282":6,"283":6,"284":6,"285":6,"286":6,"287":6,"288":6,"289":6,"290":6,"291":6,"292":6,"293":6,"294":6,"295":6},"day":{"0":7,"1":7,"2":7,"3":7,"4":7,"5":7,"6":7,"7":7,"8":7,"9":7,"10":7,"11":7,"12":7,"13":7,"14":7,"15":7,"16":7,"17":7,"18":7,"19":7,"20":7,"21":7,"22":7,"23":7,"24":7,"25":7,"26":7,"27":7,"28":7,"29":6,"30":6,"31":6,"32":6,"33":6,"34":6,"35":6,"36":6,"37":6,"38":6,"39":6,"40":5,"41":5,"42":5,"43":5,"44":5,"45":5,"46":5,"47":5,"48":5,"49":5,"50":5,"51":5,"52":5,"53":5,"54":5,"55":5,"56":4,"57":4,"58":4,"59":4,"60":4,"61":4,"62":4,"63":4,"64":4,"65":4,"66":4,"67":4,"68":4,"69":4,"70":4,"71":4,"72":4,"73":4,"74":4,"75":4,"76":4,"77":4,"78":3,"79":3,"80":3,"81":3,"82":3,"83":3,"84":3,"85":3,"86":3,"87":3,"88":3,"89":3,"90":3,"91":3,"92":3,"93":3,"94":3,"95":3,"96":3,"97":3,"98":3,"99":3,"100":3,"101":3,"102":3,"103":3,"104":3,"105":3,"106":3,"107":3,"108":3,"109":3,"110":3,"111":3,"112":3,"113":3,"114":3,"115":3,"116":3,"117":3,"118":3,"119":3,"120":3,"121":3,"122":3,"123":3,"124":3,"125":3,"126":3,"127":3,"128":3,"129":3,"130":3,"131":3,"132":3,"133":3,"134":3,"135":2,"136":2,"137":2,"138":2,"139":2,"140":2,"141":2,"142":2,"143":2,"144":2,"145":2,"146":2,"147":2,"148":2,"149":2,"150":2,"151":2,"152":2,"153":2,"154":2,"155":2,"156":2,"157":2,"158":2,"159":2,"160":2,"161":2,"162":2,"163":2,"164":2,"165":2,"166":2,"167":2,"168":2,"169":2,"170":2,"171":2,"172":2,"173":2,"174":2,"175":2,"176":2,"177":2,"178":2,"179":2,"180":2,"181":2,"182":2,"183":2,"184":2,"185":2,"186":2,"187":2,"188":2,"189":2,"190":2,"191":2,"192":1,"193":1,"194":1,"195":1,"196":1,"197":1,"198":1,"199":1,"200":1,"201":1,"202":1,"203":1,"204":1,"205":1,"206":1,"207":1,"208":1,"209":1,"210":1,"211":1,"212":1,"213":1,"214":1,"215":1,"216":1,"217":1,"218":1,"219":1,"220":1,"221":1,"222":1,"223":1,"224":1,"225":1,"226":1,"227":1,"228":1,"229":1,"230":1,"231":1,"232":1,"233":1,"234":1,"235":1,"236":1,"237":1,"238":1,"239":1,"240":1,"241":1,"242":1,"243":1,"244":1,"245":1,"246":30,"247":30,"248":30,"249":30,"250":30,"251":30,"252":30,"253":29,"254":27,"255":27,"256":27,"257":27,"258":27,"259":27,"260":27,"261":27,"262":27,"263":27,"264":26,"265":26,"266":26,"267":26,"268":26,"269":26,"270":26,"271":26,"272":26,"273":25,"274":25,"275":25,"276":25,"277":25,"278":25,"279":25,"280":25,"281":25,"282":25,"283":24,"284":24,"285":24,"286":24,"287":24,"288":24,"289":24,"290":24,"291":24,"292":24,"293":24,"294":24,"295":24},"publishedAt":{"0":1751910386000,"1":1751903484000,"2":1751902394000,"3":1751902202000,"4":1751901780000,"5":1751900580000,"6":1751900538000,"7":1751900503000,"8":1751900400000,"9":1751898600000,"10":1751896438000,"11":1751895443000,"12":1751893200000,"13":1751891244000,"14":1751888640000,"15":1751888326000,"16":1751886310000,"17":1751885728000,"18":1751883806000,"19":1751883730000,"20":1751883360000,"21":1751881860000,"22":1751878200000,"23":1751872251000,"24":1751852882000,"25":1751851500000,"26":1751850338000,"27":1751846400000,"28":1751846400000,"29":1751845905000,"30":1751827702000,"31":1751814900000,"32":1751810820000,"33":1751808600000,"34":1751805893000,"35":1751801700000,"36":1751799600000,"37":1751798700000,"38":1751771051000,"39":1751760000000,"40":1751742760000,"41":1751735400000,"42":1751730180000,"43":1751724002000,"44":1751718603000,"45":1751717975000,"46":1751716320000,"47":1751715000000,"48":1751710920000,"49":1751709900000,"50":1751706300000,"51":1751699700000,"52":1751695800000,"53":1751673600000,"54":1751673600000,"55":1751673600000,"56":1751658133000,"57":1751656529000,"58":1751655314000,"59":1751653391000,"60":1751646300000,"61":1751645460000,"62":1751641203000,"63":1751639855000,"64":1751634174000,"65":1751630220000,"66":1751628600000,"67":1751627100000,"68":1751619308000,"69":1751619306000,"70":1751619304000,"71":1751619215000,"72":1751618581000,"73":1751611228000,"74":1751587200000,"75":1751587200000,"76":1751587200000,"77":1751587200000,"78":1751585478000,"79":1751584422000,"80":1751583843000,"81":1751583034000,"82":1751576400000,"83":1751575878000,"84":1751571801000,"85":1751571612000,"86":1751571240000,"87":1751566620000,"88":1751565600000,"89":1751565120000,"90":1751562762000,"91":1751562540000,"92":1751561587000,"93":1751560089000,"94":1751559912000,"95":1751559912000,"96":1751557020000,"97":1751556906000,"98":1751555997000,"99":1751555724000,"100":1751555580000,"101":1751555220000,"102":1751554802000,"103":1751554380000,"104":1751554380000,"105":1751553895000,"106":1751553047000,"107":1751553004000,"108":1751552711000,"109":1751551809000,"110":1751551199000,"111":1751550840000,"112":1751550302000,"113":1751549495000,"114":1751547615000,"115":1751544000000,"116":1751541597000,"117":1751540100000,"118":1751539800000,"119":1751539625000,"120":1751529600000,"121":1751518178000,"122":1751506200000,"123":1751500800000,"124":1751500800000,"125":1751500800000,"126":1751500800000,"127":1751500800000,"128":1751500800000,"129":1751500800000,"130":1751500800000,"131":1751500800000,"132":1751500800000,"133":1751500800000,"134":1751500800000,"135":1751486400000,"136":1751485589000,"137":1751484133000,"138":1751484081000,"139":1751482986000,"140":1751480889000,"141":1751479680000,"142":1751478553000,"143":1751478529000,"144":1751478324000,"145":1751476980000,"146":1751476276000,"147":1751475668000,"148":1751473680000,"149":1751472545000,"150":1751472060000,"151":1751472000000,"152":1751471782000,"153":1751471192000,"154":1751470804000,"155":1751470643000,"156":1751464829000,"157":1751461918000,"158":1751458668000,"159":1751458088000,"160":1751458088000,"161":1751456411000,"162":1751455467000,"163":1751454919000,"164":1751454190000,"165":1751453807000,"166":1751451358000,"167":1751451060000,"168":1751450880000,"169":1751449500000,"170":1751441340000,"171":1751439726000,"172":1751436620000,"173":1751432400000,"174":1751421600000,"175":1751414400000,"176":1751414400000,"177":1751414400000,"178":1751414400000,"179":1751414400000,"180":1751414400000,"181":1751414400000,"182":1751414400000,"183":1751414400000,"184":1751414400000,"185":1751414400000,"186":1751414400000,"187":1751414400000,"188":1751414400000,"189":1751414400000,"190":1751414400000,"191":1751414400000,"192":1751413504000,"193":1751413320000,"194":1751407604000,"195":1751405658000,"196":1751401414000,"197":1751401380000,"198":1751400157000,"199":1751397641000,"200":1751397301000,"201":1751397060000,"202":1751395000000,"203":1751393738000,"204":1751393483000,"205":1751391676000,"206":1751391388000,"207":1751390580000,"208":1751389800000,"209":1751388260000,"210":1751388120000,"211":1751387820000,"212":1751386980000,"213":1751386480000,"214":1751384700000,"215":1751384403000,"216":1751383920000,"217":1751383320000,"218":1751382960000,"219":1751382000000,"220":1751382000000,"221":1751382000000,"222":1751382000000,"223":1751381992000,"224":1751381718000,"225":1751380672000,"226":1751379522000,"227":1751379046000,"228":1751378820000,"229":1751370979000,"230":1751367600000,"231":1751363414000,"232":1751359756000,"233":1751357244000,"234":1751338852000,"235":1751328000000,"236":1751328000000,"237":1751328000000,"238":1751328000000,"239":1751328000000,"240":1751328000000,"241":1751328000000,"242":1751328000000,"243":1751328000000,"244":1751328000000,"245":1751328000000,"246":1751241600000,"247":1751241600000,"248":1751241600000,"249":1751241600000,"250":1751241600000,"251":1751241600000,"252":1751241600000,"253":1751155200000,"254":1750982400000,"255":1750982400000,"256":1750982400000,"257":1750982400000,"258":1750982400000,"259":1750982400000,"260":1750982400000,"261":1750982400000,"262":1750982400000,"263":1750982400000,"264":1750896000000,"265":1750896000000,"266":1750896000000,"267":1750896000000,"268":1750896000000,"269":1750896000000,"270":1750896000000,"271":1750896000000,"272":1750896000000,"273":1750809600000,"274":1750809600000,"275":1750809600000,"276":1750809600000,"277":1750809600000,"278":1750809600000,"279":1750809600000,"280":1750809600000,"281":1750809600000,"282":1750809600000,"283":1750723200000,"284":1750723200000,"285":1750723200000,"286":1750723200000,"287":1750723200000,"288":1750723200000,"289":1750723200000,"290":1750723200000,"291":1750723200000,"292":1750723200000,"293":1750723200000,"294":1750723200000,"295":1750723200000},"headline":{"0":"Google Wants To Hit Net Zero By 2030 \\u2014 So It Signed A Massive Deal With A Bill Gates-Backed Startup That\'s Still Years Away From Making Energy","1":"Who could win and lose on tighter Trump AI controls? UBS weighs in","2":"Microsoft announces public preview of deep research in Azure AI foundry","3":"Why Microsoft (MSFT) is a Top Stock for the Long-Term","4":"Company News for Jul 7, 2025","5":"UiPath Stock Jumps 36% in Three Months: Time to Buy PATH?","6":"Why the CEO of the world\\u2019s large sovereign wealth fund is worried about rising US debt","7":"OpenAI\'s Altman Says He\'s No Longer a Democrat","8":"Nebius Surges 81% YTD: How Should Investors Play NBIS Stock?","9":"VIOME COLLABORATES WITH MICROSOFT TO DELIVER PREVENTIVE HEALTHCARE WITH ONE OF WORLD\'S LARGEST RNA DATASETS","10":"ChatGPT\'s Upcoming Ad Play: A Direct Threat to Google\'s Search Goldmine","11":"Microsoft introduces Azure Accelerate","12":"NTT DATA Appoints Anne-Sophie Lotgering as Europe CEO","13":"Nebius: Explosive Growth But Zero Profits","14":"The Zacks Analyst Blog Highlights Palantir, NVIDIA, Microsoft, Amazon.com and Alphabet","15":"Microsoft: Time For Trimming (Rating Downgrade)","16":"OpenAI stock compensation expense soared to 119% of revenue last year - The Information","17":"Microsoft ceases operations in Pakistan amid global restructuring","18":"MICROSOFT CORP : Buy rating from UBS","19":"European stocks\' 2025 outperformance is over, but don\'t forget the euro","20":"Netherlands Data Center Market Investment Analysis & Growth Opportunities 2025-2030: Vacancy Rate in Netherlands Data Center Spaces Drops to 5%","21":"Opinion: Here Are 7 Reasons Palantir Stock Can Plunge at Least 60%","22":"2 ETFs To Prepare You For A Potential Recession","23":"OpenAI, Oracle Deal Shows Need for Compute Power","24":"DTCR: A Good Way To Benefit From The AI Boom","25":"Winslow U.S. Large Cap Growth SMA Q1 2025 Commentary","26":"IXN: Global Tech Stocks Broke Out Again, Reiterate Buy","27":"A UN Human Rights Council report lists Microsoft among big tech companies that \\"profit\\" from Gaza genocide","28":"Microsoft reportedly met with Romero Games just a day before pulling funding \\u2014 and said absolutely nothing about what was coming","29":"Alphabet: Quiet AI Edge Wall Street Shouldn\'t Ignore","30":"The real risk of a recession, and other key points about the US economy right now","31":"Nvidia vs. Microsoft Stock: Which Will Be the First $4 Trillion Company?","32":"This CEO went from folding clothes at Nordstrom to being Jeff Bezos\\u2019 right hand man\\u2014the billionaire told him to delegate to his employees more","33":"Amazon: Don\'t Wait Till It Enters Beast Mode","34":"IGA: Strong Performance From Foreign Exposure And Fully-Covered Distribution","35":"Amazon vs. Microsoft: Which Cloud Computing Giant Is the Better Buy?","36":"What To Expect From the Magnificent Seven in the Second Half of 2025","37":"NYLI Income Builder Fund Q1 2025 Commentary","38":"DGRO: Much Smarter Than A High-Yield ETF","39":"The Broken Microsoft Pact: Layoffs and Performance Management","40":"DA Davidson Calls Microsoft (MSFT) Its Top Mega-Cap Pick \\u2014 New $600 Target Set","41":"2 Unstoppable Growth Stocks to Hold for the Next 20 Years","42":"Prediction: This Artificial Intelligen

<>:4: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\d'
C:\Users\cleme\AppData\Local\Temp\ipykernel_15976\597535258.py:4: SyntaxWarning: invalid escape sequence '\d'
  with open('..\data\output\dataset\data_2025_07_08.json', "r", encoding="utf-8") as f:

In [35]:
output_data["options"]

{'cluster_buy': ['Price within spread'],
 'cluster_sell': ['Price within spread'],
 'nb_option_buy': [105],
 'nb_option_sell': [83],
 'buy_mean_volume': [4.261363636363637],
 'sell_mean_volume': [9.121212121212121],
 'current_price': 293.94,
 'low_analyst_price_targets': 115.0,
 'high_analyst_price_targets': 500.0,
 'mean_analyst_price_targets': 306.07172,
 'median_analyst_price_targets': 303.0}

In [30]:
def read_json_file(data):
    parsed = json.loads(data)
    df = pd.DataFrame.from_dict(parsed)
    return df

In [ ]:
read_json_file(output_data["info_company"])

,index,year,month,day,publishedAt,headline,summary,source,url,API
0,0,2025,7,7,1751910386000,Google Wants To Hit Net Zero By 2030 — So It S...,Google has signed a groundbreaking agreement w...,Yahoo,https://finnhub.io/api/news?id=28cf0a4d42b955b...,finnhub_news
1,1,2025,7,7,1751903484000,Who could win and lose on tighter Trump AI con...,Investing.com -- UBS analysts warn that the re...,Yahoo,https://finnhub.io/api/news?id=9725a07c58d9565...,finnhub_news
2,2,2025,7,7,1751902394000,Microsoft announces public preview of deep res...,Microsoft Corp:* Microsoft: announces public p...,Finnhub,https://finnhub.io/api/news?id=68644dcd2eee8e0...,finnhub_news
3,3,2025,7,7,1751902202000,Why Microsoft (MSFT) is a Top Stock for the Lo...,"Wondering how to pick strong, market-beating s...",Yahoo,https://finnhub.io/api/news?id=ea3f5ffee57a491...,finnhub_news
4,4,2025,7,7,1751901780000,"Company News for Jul 7, 2025","Companies in The News Are: SNPS, DDOG, MSFT, TRIP",Yahoo,https://finnhub.io/api/news?id=ae494183a17b8fd...,finnhub_news
...,...,...,...,...,...,...,...,...,...,...
291,59,2025,6,24,1750723200000,Microsoft Offers Free Windows 10 Extended Secu...,Microsoft continues to support your PC only if...,CNET,https://www.cnet.com/tech/computing/microsoft-...,api_news_org
292,42,2025,6,24,1750723200000,heise-Angebot: Live-Webinar: Apple-Geräte effi...,Lernen Sie im Live-Webinar bewährte Methoden u...,heise online,https://www.heise.de/news/Live-Webinar-Apple-G...,api_news_org
293,93,2025,6,24,1750723200000,Microsoft annonce le casque VR Meta Quest 3S X...,Le casque Meta Quest 3S Xbox Edition est dispo...,Journal du geek,https://www.journaldugeek.com/2025/06/24/micro...,api_news_org
294,6,2025,6,24,1750723200000,Microsoft Sets New 60-Day Limit For System Res...,An anonymous reader quotes a report from Extre...,Slashdot.org,https://tech.slashdot.org/story/25/06/23/21402...,api_news_org
295,3,2025,6,24,1750723200000,A week in Xbox VR with Microsoft and Meta’s ne...,Microsoft and Meta announced an Xbox-branded Q...,The Verge,https://www.theverge.com/hands-on/690978/meta-...,api_news_org

In [ ]:
read_json_file(output_data["info_company"])
read_json_file(output_data["news"]["company_news"])
read_json_file(output_data["news"]["country_news"])

,country,currency,finnhubIndustry,marketCapitalization,competitor_lst,begin_analyst_period,end_analyst_period,delta_number_days_analyst,mean_sell,mean_strongBuy,mean_strongSell,insider_sentiment
0,US,USD,Technology,3.699326e+06,"MSFT, ORCL, NOW, PANW, CRWD, FTNT, ZS, GEN, RB...",2025-04-01,2025-07-01,91,0.0,1.0,0.0,-1