In [12]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.

In [1]:
from API.preprocessing.get_company_news import create_news_dataset

create_news_dataset(business_name="Tesla", business_ticker="TSLA")

Date des articles de récupération des articles 2025-03-09
News recover from api_news_org
News sur 6 days 20:00:43 jours
News recover from finhub
News processing done and save

,index,year,month,day,publishedAt,headline,summary,source,url,API
0,0,2025,3,22,2025-03-22 23:48:53,Is Tesla (TSLA) Widely Held by Individuals in ...,We recently compiled a list of the 12 Most Wid...,Yahoo,https://finnhub.io/api/news?id=a968b590896e60c...,finnhub_news
1,1,2025,3,22,2025-03-22 22:00:00,Tesla investors at a loss as Elon Musk drags d...,"Tesla finds itself in uncharted territory, now...",Yahoo,https://finnhub.io/api/news?id=109c2d5c15643e5...,finnhub_news
2,2,2025,3,22,2025-03-22 21:50:45,X Suspends Accounts in Turkey After Government...,X has once again implemented restrictions at t...,Yahoo,https://finnhub.io/api/news?id=82b7bdf5b9b152e...,finnhub_news
3,3,2025,3,22,2025-03-22 21:44:16,Elon Musk Quotes Warren Buffett Metaphor On St...,Tesla Inc. (NASDAQ:TSLA) CEO Elon Musk invoked...,Yahoo,https://finnhub.io/api/news?id=31ba5d532d9e4c3...,finnhub_news
4,4,2025,3,22,2025-03-22 19:11:58,Tesla Vs. BYD: TSLA Stock Tries To Halt Slide ...,"Tesla has sold off as Elon Musk spurs brand ""d...",Yahoo,https://finnhub.io/api/news?id=dd8f492a6360c4c...,finnhub_news
...,...,...,...,...,...,...,...,...,...,...
286,53,2025,3,10,2025-03-10 00:00:00,Elon Musk Searching for Mysterious Billionaire...,None,Yahoo Entertainment,https://consent.yahoo.com/v2/collectConsent?se...,api_news_org
287,4,2025,3,10,2025-03-10 00:00:00,Ford’s Tesla Supercharger adapters are now on ...,Ford is making some changes to how it handles ...,The Verge,https://www.theverge.com/news/627230/ford-nacs...,api_news_org
288,87,2025,3,10,2025-03-10 00:00:00,Tesla Showroom Set on Fire,Authorities in France are investigating a susp...,Hindustan Times,https://www.hindustantimes.com/trending/tesla-...,api_news_org
289,47,2025,3,10,2025-03-10 00:00:00,Musk Melts Down as Tesla Stock Price Plunges,None,Yahoo Entertainment,https://consent.yahoo.com/v2/collectConsent?se...,api_news_org
290,49,2025,3,9,2025-03-09 00:00:00,Tesla Is Flailing in China and the Rapid Rise ...,None,Yahoo Entertainment,https://consent.yahoo.com/v2/collectConsent?se...,api_news_org

In [3]:
from API.preprocessing.get_options_preprocessing import create_options_dataset
a = create_options_dataset("TSLA")

test
Expirations Dates of the options ('2025-03-28', '2025-04-04', '2025-04-11', '2025-04-17', '2025-04-25', '2025-05-02', '2025-05-16', '2025-06-20', '2025-07-18', '2025-08-15', '2025-09-19', '2025-11-21', '2025-12-19', '2026-01-16', '2026-03-20', '2026-06-18', '2026-09-18', '2026-12-18', '2027-01-15', '2027-06-17')

In [4]:
a

,cluster_buy,cluster_sell,nb_option_buy,nb_option_sell,buy_mean_volume,sell_mean_volume,current_price,low_analyst_price_targets,high_analyst_price_targets,mean_analyst_price_targets,median_analyst_price_targets
0,Price within spread,Price within spread,2161,2034,341.044455,377.881399,248.71,120.0,550.0,338.5826,371.5