In [1]:
from machine_learning.create_ml_dataset import create_dataset_from_all_file
from machine_learning.create_label_to_predict import create_label_from_scoring

In [2]:
### A faire
#  Ajouter des points négatif pour les dates plus anciennes 
# # date la plus récente = +2
# 2eme date plus récente +1
# et apres 0
# et apres -1

In [2]:
ml_dataset = create_dataset_from_all_file()

Machine learning dataset create

In [4]:
# df["decision_pack"] contiendra {decision, score_total, details}
ml_dataset["decision_pack"] = ml_dataset.apply(lambda x: create_label_from_scoring(x.to_dict()), axis=1)

# Colonnes pratiques à partcers
ml_dataset["decision_label"] = ml_dataset["decision_pack"].apply(lambda d: d["decision"])
ml_dataset["decision_score"] = ml_dataset["decision_pack"].apply(lambda d: d["score_total"])

In [5]:
def replace_direction_value(value):
    if value=="Down":
        return -1
    elif value=="Up":
        return 1
    elif value=="Flat":
        return 0

In [6]:
ml_dataset["this_month_most_direction"] = ml_dataset["this_month_most_direction"].apply(lambda x : replace_direction_value(x))
ml_dataset["last_month_most_direction"] = ml_dataset["last_month_most_direction"].apply(lambda x : replace_direction_value(x))
ml_dataset["year_to_date_direction"] = ml_dataset["year_to_date_direction"].apply(lambda x : replace_direction_value(x))
ml_dataset["one_year_rolling_period_most_direction"] = ml_dataset["one_year_rolling_period_most_direction"].apply(lambda x : replace_direction_value(x))
ml_dataset["five_year_rolling_period_most_direction"] = ml_dataset["five_year_rolling_period_most_direction"].apply(lambda x : replace_direction_value(x))

In [7]:
def replace_trend_value(trend_value):
    if "Very bullish" in trend_value:
        return 2
    if "Bullish" in trend_value:
        return 1
    if "Stagnant" in trend_value:
        return 0
    if "Bearish" in trend_value:
        return -1
    if "Very bearish" in trend_value:
        return -2

In [8]:
ml_dataset["this_month_trend"] = ml_dataset["this_month_trend"].apply(lambda x : replace_trend_value(x))
ml_dataset["last_month_trend"] = ml_dataset["last_month_trend"].apply(lambda x : replace_trend_value(x))
ml_dataset["year_to_date_trend"] = ml_dataset["year_to_date_trend"].apply(lambda x : replace_trend_value(x))
ml_dataset["one_year_rolling_trend"] = ml_dataset["one_year_rolling_trend"].apply(lambda x : replace_trend_value(x))
ml_dataset["five_year_rollingtrend"] = ml_dataset["five_year_rollingtrend"].apply(lambda x : replace_trend_value(x))

In [9]:
ml_dataset["this_month_volume"] = ml_dataset["this_month_volume"].apply(lambda x : replace_trend_value(x))
ml_dataset["last_month_volume"] = ml_dataset["last_month_volume"].apply(lambda x : replace_trend_value(x))
ml_dataset["year_to_date_volume"] = ml_dataset["year_to_date_volume"].apply(lambda x : replace_trend_value(x))
ml_dataset["one_year_rolling_volume"] = ml_dataset["one_year_rolling_volume"].apply(lambda x : replace_trend_value(x))
ml_dataset["five_year_rolling_volume"] = ml_dataset["five_year_rolling_volume"].apply(lambda x : replace_trend_value(x))

In [10]:
import numpy as np

In [11]:
ml_dataset["analyst_mean_sentiment_distribution"] = ml_dataset["analyst_sentiment_distribution"].apply(lambda x : float(x["mean_sentiment"]))
ml_dataset["analyst_positif_sentiment_distribution"] = ml_dataset["analyst_sentiment_distribution"].apply(lambda x : float(x["positif"])/100)
ml_dataset["analyst_negatif_sentiment_distribution"] = ml_dataset["analyst_sentiment_distribution"].apply(lambda x : float(x["negatifs"])/100)
ml_dataset.drop(columns=["analyst_sentiment_distribution"], axis=1, inplace=True)

In [12]:
ml_dataset["current_price"] = ml_dataset["analyst_price_target"].apply(lambda x : x["current"])
ml_dataset["high_price_target"] = ml_dataset["analyst_price_target"].apply(lambda x : x["high"])
ml_dataset["low_price_target"] = ml_dataset["analyst_price_target"].apply(lambda x : x["low"])
ml_dataset["mean_price_target"] = ml_dataset["analyst_price_target"].apply(lambda x : x["mean"])
ml_dataset["median_price_target"] = ml_dataset["analyst_price_target"].apply(lambda x : x["median"])
ml_dataset.drop(columns=["analyst_price_target"], axis=1, inplace=True)

In [13]:
ml_dataset.drop(columns=["decision_pack"], axis=1, inplace=True)

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
enc = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
col_enc = enc.fit_transform(ml_dataset[["company_name", "finnhubIndustry", "analyst_recommendation_of_the_month"]])
col_enc

,company_name_anf,company_name_msft,company_name_pfe,company_name_sbux,company_name_tsla,company_name_wmt,finnhubIndustry_Automobiles,"finnhubIndustry_Hotels, Restaurants & Leisure",finnhubIndustry_Pharmaceuticals,finnhubIndustry_Retail,finnhubIndustry_Technology,analyst_recommendation_of_the_month_buy,analyst_recommendation_of_the_month_hold
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
164,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
165,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
166,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
167,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [17]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [18]:
ml_dataset.drop(columns=["company_name", "finnhubIndustry", "analyst_recommendation_of_the_month"], axis=1, inplace=True)
X = pd.concat([col_enc, ml_dataset], axis=1).drop(["decision_label"])

KeyError: "['decision_label'] not found in axis"

In [ ]:
label_encoder = LabelEncoder()

label = ml_dataset["decision_label"]
values = label_encoder.fit_transform(label)
ml_dataset["decision_label"] = values

In [ ]:
ml_dataset

,company_name_anf,company_name_msft,company_name_pfe,company_name_sbux,company_name_tsla,company_name_wmt,finnhubIndustry_Automobiles,"finnhubIndustry_Hotels, Restaurants & Leisure",finnhubIndustry_Pharmaceuticals,finnhubIndustry_Retail,...,decision_label,decision_score,analyst_mean_sentiment_distribution,analyst_positif_sentiment_distribution,analyst_negatif_sentiment_distribution,current_price,high_price_target,low_price_target,mean_price_target,median_price_target
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,2.742,0.67,0.6667,0.3333,86.9300,141.0,82.0,113.36889,119.32
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1,-0.836,0.67,0.6667,0.3333,88.2400,141.0,82.0,113.36889,119.32
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1,-0.399,0.67,0.6667,0.3333,89.3400,141.0,82.0,113.36889,119.32
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1,-0.552,0.75,0.7500,0.2500,92.1000,141.0,82.0,113.36889,119.32
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1,-0.391,0.75,0.7500,0.2500,89.1900,141.0,82.0,113.36889,119.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1,0.981,0.97,0.9655,0.0345,104.0450,130.0,64.0,110.24324,110.00
164,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1,0.997,0.97,0.9655,0.0345,103.6419,130.0,64.0,110.27027,110.00
165,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0,6.603,0.97,0.9655,0.0345,100.9900,130.0,64.0,110.40541,110.00
166,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1,1.108,0.97,0.9655,0.0345,100.8500,130.0,64.0,110.29730,110.00
167,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1,0.646,0.97,0.9655,0.0345,100.0000,130.0,64.0,110.56757,110.00

In [ ]:
ml_dataset.select_dtypes(include=['object'])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[168 rows x 0 columns]

# faire les labels pour les dates
ml_dataset["date_bourse"]